#!/usr/bin/env python3
"""Download experimental structures for the app's presets and bake their Cα coordinates into Kotlin.

For each preset chain, the PDB chain's observed residues are aligned to the preset's (UniProt-checked)
sequence; aligned residues get the PDB Cα position, unaligned ones get none. Prints an alignment report.
Run from the repo root:  python3 tools/extract_native.py
"""
import re, sys, urllib.request

THREE = {'ALA':'A','ARG':'R','ASN':'N','ASP':'D','CYS':'C','GLN':'Q','GLU':'E','GLY':'G','HIS':'H','ILE':'I',
         'LEU':'L','LYS':'K','MET':'M','PHE':'F','PRO':'P','SER':'S','THR':'T','TRP':'W','TYR':'Y','VAL':'V',
         'MSE':'M','HSD':'H','HSE':'H','HIE':'H','HID':'H','CYX':'C','SEC':'C'}

# preset id -> (PDB id, [PDB chain for each preset chain])
SOURCES = {
    'chignolin': ('1UAO', ['A']), 'trpcage': ('1L2Y', ['A']), 'gb1': ('1PGA', ['A']), 'villin': ('1YRF', ['A']),
    'melittin': ('2MLT', ['A']), 'glucagon': ('1GCN', ['A']), 'glp1': ('1D0R', ['A']),
    'insulin': ('4INS', ['A', 'B']), 'bpti': ('4PTI', ['A']), 'lysozyme': ('193L', ['A']),
    'ubq': ('1UBQ', ['A']), 'myoglobin': ('1A6M', ['A']), 'gfp': ('1GFL', ['A']),
    'gcn4': ('2ZTA', ['A', 'B']), 'hemoglobin': ('2HHB', ['A', 'B', 'C', 'D']), 'sickle': ('2HBS', ['A', 'B', 'C', 'D']),
    'rnhi': ('2BNH', ['A']), 'importin': ('1EE4', ['A']), 'pectate': ('1AIR', ['A']), 'gbeta': ('1TBG', ['B']),
    'mbp': ('1ANF', ['A']), 'tim': ('1TIM', ['A']), 'tim2': ('1TIM', ['A', 'B']), 'adk': ('4AKE', ['A']),
    'mfpa': ('2BM4', ['A']), 'mfpa2': ('2BM4', ['A', 'B']), 'ferritin': ('2FHA', ['A']), 't4l': ('2LZM', ['A']),
    'calmodulin': ('1CLL', ['A']), 'top7': ('1QYS', ['A']), 'ankyrin': ('1N0R', ['A']), 'ctpr3': ('1NA0', ['A']),
    'antifreeze': ('1M8N', ['A']), 'titin': ('1TIT', ['A']),
}

def presets():
    src = open('android/core/src/main/java/com/hydrophobiccollapse/Proteins.kt', encoding='utf-8').read()
    consts = dict(re.findall(r'private const val (\w+) = "([A-Z]+)"', src))
    out = {}
    for m in re.finditer(r'Protein\("(\w+)", "[^"]*",\s*(listOf\([^)]*\)|List\(\d+\) \{ \w+ \})', src):
        pid, chains = m.group(1), m.group(2)
        items = re.findall(r'"([A-Z]+)"|\b([A-Z][A-Z0-9]+)\b', chains[len('listOf('):] if chains.startswith('listOf') else '')
        seqs = [a or consts[b] for a, b in items if a or b in consts]
        out[pid] = seqs
    return out

def fetch(pdb):
    with urllib.request.urlopen(f'https://files.rcsb.org/download/{pdb}.pdb', timeout=60) as r:
        return r.read().decode()

def ca_chains(text):
    chains = {}
    for line in text.splitlines():
        if line.startswith('ENDMDL'): break          # first model only
        if not line.startswith(('ATOM', 'HETATM')) or line[12:16].strip() != 'CA': continue
        if line[16] not in ' A': continue           # first alternate location
        res = THREE.get(line[17:20].strip())
        if not res: continue
        key = (line[22:26], line[26])
        ch = chains.setdefault(line[21], {})
        if key not in ch: ch[key] = (res, float(line[30:38]), float(line[38:46]), float(line[46:54]))
    return {c: list(v.values()) for c, v in chains.items()}

def align(a, b):
    """Global alignment with free end gaps. Returns map from index in a to index in b."""
    n, m = len(a), len(b)
    S = [[0] * (m + 1) for _ in range(n + 1)]; T = [[0] * (m + 1) for _ in range(n + 1)]
    for i in range(1, n + 1):
        for j in range(1, m + 1):
            d = S[i-1][j-1] + (2 if a[i-1] == b[j-1] else -1)
            u = S[i-1][j] - (0 if j == m else 2); l = S[i][j-1] - (0 if i == n else 2)
            S[i][j], T[i][j] = max((d, 0), (u, 1), (l, 2))
    i, j, mp = n, m, {}
    while i > 0 and j > 0:
        t = T[i][j]
        if t == 0: mp[i-1] = j-1; i -= 1; j -= 1
        elif t == 1: i -= 1
        else: j -= 1
    return mp

def main():
    P = presets()
    lines = []
    for pid, (pdb, pchains) in SOURCES.items():
        seqs = P[pid]
        assert len(seqs) == len(pchains), (pid, len(seqs))
        cas = ca_chains(fetch(pdb))
        coords, ident, cover, total = [], 0, 0, 0
        for seq, cid in zip(seqs, pchains):
            obs = cas[cid]
            mp = align(seq, ''.join(r[0] for r in obs))
            for k in range(len(seq)):
                total += 1
                if k in mp:
                    r = obs[mp[k]]; cover += 1; ident += r[0] == seq[k]
                    coords.append(f'{round(r[1]*10)},{round(r[2]*10)},{round(r[3]*10)}')
                else:
                    coords.append('_')
        print(f'{pid:11} {pdb}  coverage {cover}/{total}  identity {ident}/{cover}', file=sys.stderr)
        assert cover >= 0.8 * total and ident >= 0.9 * cover, pid
        lines.append(f'        "{pid}" to ("PDB {pdb}" to "{";".join(coords)}"),')
    kt = ('package com.hydrophobiccollapse\n\n'
          '// Generated by tools/extract_native.py from RCSB PDB files: Cα positions in tenths of an Å,\n'
          '// one "x,y,z" per preset residue ("_" where the structure has no residue). Do not edit by hand.\n'
          'internal object NativeStructures {\n    val encoded: Map<String, Pair<String, String>> = mapOf(\n' + '\n'.join(lines) + '\n    )\n}\n')
    open('android/core/src/main/java/com/hydrophobiccollapse/NativeStructures.kt', 'w', encoding='utf-8', newline='\n').write(kt)

if __name__ == '__main__':
    main()
